### ISSUE TITLE
Shader compilation error on Linux Intel GPU

### ISSUE THREAD

**Issue by gilzoide** [aferust/drawee#1]
While running the game on Intel GPU on Linux, it aborted on the call to `initShader` from `loadShaderHero` trying to compile the fragment shader with the message `"failed to compile: 0:2(2): error: syntax error, unexpected NEW_IDENTIFIER"`.
Running with NVidia GPU worked.

By the message, it seems `precision mediump float;`  is not supported by all OpenGL drivers.
Precision specifiers [seem to only matter on OpenGL ES]( https://www.khronos.org/opengl/wiki/Type_Qualifier_(GLSL)#Precision_qualifiers ), so I think they should be either removed or guarded by `#ifdef GL_ES` blocks, depending on whether or not you want to support OpenGL ES.
```glsl
#ifdef GL_ES
precision mediump float;
#endif
```

**Comment by aferust** [comment]
I just removed it thank you.
